// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEZOZEOzD3Mrk1H067hvXT46im66HM8J0',
    appId: '1:298035315344:web:3b19e42abc34c440dd8e15',
    messagingSenderId: '298035315344',
    projectId: 'pet-shop-ccec0',
    authDomain: 'pet-shop-ccec0.firebaseapp.com',
    storageBucket: 'pet-shop-ccec0.appspot.com',
    measurementId: 'G-2X4WFXZPRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-zicf3M6y1wdt34pPAT2UpRk4RFqRWoU',
    appId: '1:298035315344:android:54fcf72b942a3a0edd8e15',
    messagingSenderId: '298035315344',
    projectId: 'pet-shop-ccec0',
    storageBucket: 'pet-shop-ccec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAz_vf5DwsQCaVrmto9vApIb0Q-bj8kdU',
    appId: '1:298035315344:ios:35920a2e63e24d14dd8e15',
    messagingSenderId: '298035315344',
    projectId: 'pet-shop-ccec0',
    storageBucket: 'pet-shop-ccec0.appspot.com',
    iosBundleId: 'com.example.projeto02app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHJmie0SoDXD3GWOA6AfUP4ZNNtNjdhJ8',
    appId: '1:624700976893:web:c5562b730b59cd2d1e1894',
    messagingSenderId: '624700976893',
    projectId: 'sweet-coffee-f735d',
    authDomain: 'sweet-coffee-f735d.firebaseapp.com',
    storageBucket: 'sweet-coffee-f735d.appspot.com',
    measurementId: 'G-YYBXYWP8JL',
  );

}